version: '3.4'

services:
  inventura-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PlanesCarsAndTrains4321
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks: 
      - inventuranet
  identity-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PlanesCarsAndTrains4321
      - MSSQL_PID=Developer
    ports:
      - 1402:1433
    networks: 
      - inventuranet
  identity-server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./src/IdentityServerAspNetIdentity/Dockerfile
    environment: 
      - ConnectionStrings:DefaultConnection=Data Source=identity-sql,1433;User=sa;Password=PlanesCarsAndTrains4321;Initial Catalog=IdentityDb
    ports:
      - 5001:5001
    networks:
      - inventuranet
    links:
      - identity-sql
    depends_on:
      - identity-sql
  public-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./src/PublicApi/Dockerfile
    environment: 
      - ConnectionStrings:DbConnection=Server=inventura-sql,1433;User=sa;Password=PlanesCarsAndTrains4321;Initial Catalog=AppDb
      - ConnectionStrings:IdentityAuthority=http://identity-server:5001
      - Issuer=http://localhost:5001,http://10.0.2.2:5001
    ports:
      - 5098:5098
    networks:
      - inventuranet
    links:
      - inventura-sql
      - identity-server
    depends_on:
      - inventura-sql
      - identity-server
networks:
  inventuranet:
    driver: bridge
